### ISSUE TITLE
raise KRPCTimeout

### ISSUE THREAD

**Issue by d33tah** [drxzcl/lightdht#4]
```
$ python lightdht.py
KRPC request to ('67.215.242.139', 6881)
Traceback (most recent call last):
  File "lightdht.py", line 312, in <module>
    with dht1:
  File "lightdht.py", line 135, in __enter__
    self.start()
  File "lightdht.py", line 123, in start
    DEFAULT_ID = self._server.ping(os.urandom(20), DEFAULT_NODE)['id']
  File "/tmp/lightdht/krpcserver.py", line 198, in ping
    return self._synctrans(q, node)
  File "/tmp/lightdht/krpcserver.py", line 183, in _synctrans
    raise KRPCTimeout
krpcserver.KRPCTimeout
```

How do I actually run it? Should I open any ports other than 54767/tcp and 54767/udp?

**Comment by drxzcl** [comment]
I'm guessing the DEFAULT_NODE is no longer operational. Try using a known-good DHT peer (for example, your own torrent client) and see if the problem goes away.

**Comment by d33tah** [comment]
@drxzcl: how about replacing DEFAULT_NODE with `socket.gethostbyname('router.bittorrent.com')`?
